/**
 * Single source of truth for review IDs.
 *
 * Every `data-review-id` in the app must come from this file — never a hand-typed
 * string in a component. This guarantees the DOM attribute and the registry.json key
 * are always the same string. See registry/README.md for the full convention.
 */

const pad = (n: number) => String(n).padStart(2, "0");

export const IDS = {
  siteHeader: {
    root: "xc-site-header",
    logo: "xc-site-header.logo",
    navItem: (n: number) => `xc-site-header.nav-item-${pad(n)}`,
    ctaDemo: "xc-site-header.cta-demo",
  },
  hero: {
    root: "xc-hero",
    eyebrow: "xc-hero.eyebrow",
    headline: "xc-hero.headline",
    paragraph: "xc-hero.paragraph",
    ctaPrimary: "xc-hero.cta-primary",
    ctaSecondary: "xc-hero.cta-secondary",
    trustStatement: (n: number) => `xc-hero.trust-statement-${pad(n)}`,
    trustStripLabel: "xc-hero.trust-strip-label",
    flowInputNode: (n: number) => `xc-hero.flow-input-node-${pad(n)}`,
    flowOutputNode: (n: number) => `xc-hero.flow-output-node-${pad(n)}`,
  },
  operationalGap: {
    root: "xc-operational-gap",
    eyebrow: "xc-operational-gap.eyebrow",
    heading: "xc-operational-gap.heading",
    paragraph: "xc-operational-gap.paragraph",
    transitionStatement: "xc-operational-gap.transition-statement",
    card: (n: number) => `xc-operational-gap.card-${pad(n)}`,
  },
  problemFigures: {
    root: "xc-problem-figures",
    eyebrow: "xc-problem-figures.eyebrow",
    heading: "xc-problem-figures.heading",
    paragraph: "xc-problem-figures.paragraph",
    grid: "xc-problem-figures.grid",
    statCard: (n: number) => `xc-problem-figures.stat-card-${pad(n)}`,
  },
  platformOverview: {
    root: "xc-platform-overview",
    eyebrow: "xc-platform-overview.eyebrow",
    heading: "xc-platform-overview.heading",
    paragraph: "xc-platform-overview.paragraph",
    dashboard: "xc-platform-overview.dashboard",
    sidebarItem: (n: number) => `xc-platform-overview.sidebar-item-${pad(n)}`,
    topControl: (n: number) => `xc-platform-overview.top-control-${pad(n)}`,
    kpiCard: (n: number) => `xc-platform-overview.kpi-card-${pad(n)}`,
    workQueueItem: (n: number) => `xc-platform-overview.work-queue-item-${pad(n)}`,
    obligationItem: (n: number) => `xc-platform-overview.obligation-item-${pad(n)}`,
    exceptionReasonItem: (n: number) => `xc-platform-overview.exception-reason-item-${pad(n)}`,
    integrationItem: (n: number) => `xc-platform-overview.integration-item-${pad(n)}`,
    highlightsHeading: "xc-platform-overview.highlights-heading",
    highlightsParagraph: "xc-platform-overview.highlights-paragraph",
    highlightCard: (n: number) => `xc-platform-overview.highlight-card-${pad(n)}`,
    closingStatement: "xc-platform-overview.closing-statement",
    ctaPrimary: "xc-platform-overview.cta-primary",
    ctaSecondary: "xc-platform-overview.cta-secondary",
  },
  contractX: {
    root: "xc-contractx",
    eyebrow: "xc-contractx.eyebrow",
    heading: "xc-contractx.heading",
    paragraph: "xc-contractx.paragraph",
    cta: "xc-contractx.cta",
    feature: (n: number) => `xc-contractx.feature-${pad(n)}`,
    sourceTab: (n: number) => `xc-contractx.source-tab-${pad(n)}`,
    workflowStep: (n: number) => `xc-contractx.workflow-step-${pad(n)}`,
    findingPanel: "xc-contractx.finding-panel",
    findingStatement: "xc-contractx.finding-statement",
    findingEvidence: (n: number) => `xc-contractx.finding-evidence-${pad(n)}`,
    findingRecommendedAction: "xc-contractx.finding-recommended-action",
    closingStatement: "xc-contractx.closing-statement",
    ctaPrimary: "xc-contractx.cta-primary",
    ctaSecondary: "xc-contractx.cta-secondary",
  },
  enterpriseIntegrations: {
    root: "xc-integrations",
    eyebrow: "xc-integrations.eyebrow",
    heading: "xc-integrations.heading",
    paragraph: "xc-integrations.paragraph",
    carousel: "xc-integrations.carousel",
    integrationCard: (n: number) => `xc-integrations.integration-card-${pad(n)}`,
    prevControl: "xc-integrations.prev-control",
    nextControl: "xc-integrations.next-control",
    paginationDot: (n: number) => `xc-integrations.pagination-dot-${pad(n)}`,
    closingText: "xc-integrations.closing-text",
  },
  agenticOverview: {
    root: "xc-agentic",
    eyebrow: "xc-agentic.eyebrow",
    heading: "xc-agentic.heading",
    paragraph: "xc-agentic.paragraph",
    centerLabel: "xc-agentic.center-label",
    capabilityCard: (n: number) => `xc-agentic.capability-card-${pad(n)}`,
  },
  deploymentSecurity: {
    root: "xc-deployment-security",
    badge: "xc-deployment-security.badge",
    heading: "xc-deployment-security.heading",
    paragraph: "xc-deployment-security.paragraph",
    card: (n: number) => `xc-deployment-security.card-${pad(n)}`,
  },
  footer: {
    root: "xc-footer",
    brandBlock: "xc-footer.brand-block",
    socialLink: (n: number) => `xc-footer.social-link-${pad(n)}`,
    navColumn: (n: number) => `xc-footer.nav-column-${pad(n)}`,
    newsletterPanel: "xc-footer.newsletter-panel",
    newsletterHeading: "xc-footer.newsletter-heading",
    newsletterBody: "xc-footer.newsletter-body",
    newsletterInput: "xc-footer.newsletter-input",
    newsletterSubmit: "xc-footer.newsletter-submit",
    newsletterSuccess: "xc-footer.newsletter-success",
    newsletterError: "xc-footer.newsletter-error",
    systemStatus: "xc-footer.system-status",
    copyright: "xc-footer.copyright",
    legalLink: (n: number) => `xc-footer.legal-link-${pad(n)}`,
  },
} as const;
